name: beamer_module
description: "Help Applying Beamer in Flutter"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/beamer_module

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  beamer: #@add
  flutter:
    sdk: flutter
  june_flow_util:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/beamer_module/
  uses-material-design: true